name: multiphylstm
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - pip
  - numpy=1.19.2          # ✅ versión exacta esperada por TF 1.15.5
  - scipy=1.4.1           # ✅ requerida por TF 1.15.5 y evita conflictos
  - matplotlib=3.3
  - pandas=1.1
  - scikit-learn=0.24
  - h5py=2.10
  - keras=2.3.1
  - protobuf=3.17
  - jupyter
  - notebook
  - ipykernel
  - ipywidgets
  - jupyterlab
  - seaborn
  - six=1.16.0            # ✅ requerido por TF
  - gast=0.3.3            # ✅ requerido por TF
  - absl-py=0.15.0        # ✅ recomendado por NVIDIA TF
  - pip:
      - nvidia-pyindex
      # ❗️NO incluir aquí nvidia-tensorflow → se instala luego con pip manualmente


